### ISSUE TITLE
Issue parsing MSG file

### ISSUE THREAD

**Issue by luskbo** [SpamScope/mail-parser#28]
Having issues parsing a .msg files. 
Did install the dependencies, and using python3.5

Ran simple test:
```
import mailparser
import json

fp = open("messagefile.msg", "r")

# tried to read in file directly with file in same directory. 
#mail = mailparser.parse_from_file('messagefile.msg')

# tried to read in file as a file object
mail = mailparser.parse_from_file_obj(fp)

print(mail.body)

```

```
Traceback (most recent call last):
  File "mail.py", line 12, in <module>
    print(mail.body)
  File "/opt/testenv/lib/python3.5/site-packages/mail_parser-3.3.1-py3.5.egg/mailparser/mailparser.py", line 491, in body
    return "\n--- mail_boundary ---\n".join(self.text_plain)
TypeError: can only join an iterable
```

**Comment by fedelemantuano** [comment]
If you have an Outlook msg you should use:

```
>>> mail = mailparser.parse_from_file_msg('messagefile.msg')
>>> print(mail.body)
```

**Comment by luskbo** [comment]
Thanks for the quick reply, but that is not working.
I receive the same error.
See script execution and output below:

```
(testenv) user@system:/opt/testenv/scripts$ cat mail.py
import mailparser
import json

fp = open("messagefile.msg", "r")
mail = mailparser.parse_from_file_msg('messagefile.msg')
print(mail.body)


(testenv) user@system:/opt/testenv/scripts$ python mail.py
Traceback (most recent call last):
  File "mail.py", line 11, in <module>
    print(mail.body)
  File "/opt/testenv/lib/python3.5/site-packages/mail_parser-3.3.1-py3.5.egg/mailparser/mailparser.py", line 491, in body
    return "\n--- mail_boundary ---\n".join(self.text_plain)
TypeError: can only join an iterable
```

**Comment by fedelemantuano** [comment]
Did you install libemail-outlook-message-perl?
You can try the docker image. 

If parsing fails, can you send me the raw mail.

**Comment by luskbo** [comment]
I do have libemail-outlook-message-perl installed. 
Figured out the problem though. 
Original email was corrupt. Re ran with additional .msg files and all worked as expected.
Will just handle the exception in the future in case this happens again.
Thanks for the assistance.
