### ISSUE TITLE
mail-parser fails to install depending on locale

### ISSUE THREAD

**Issue by rudymatela** [SpamScope/mail-parser#30]
mail-parser currently fails to install depending on system locale (`LC_CTYPE`), like so:

```
$ LC_CTYPE=C pip install mail-parser --user
Collecting mail-parser
  Using cached https://files.pythonhosted.org/packages/10/fa/988a3fe204d7cca689d75e623adf45a2f57c43e55603b73b7ffaf092a7e0/mail-parser-3.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k3_u6ooo/mail-parser/setup.py", line 28, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6050: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-k3_u6ooo/mail-parser/
```

If an UTF-8 locale is provided, it installs ok:

```
$ LC_CTYPE=en_US.utf8 pip install mail-parser --user
Collecting mail-parser
  Using cached https://files.pythonhosted.org/packages/10/fa/988a3fe204d7cca689d75e623adf45a2f57c43e55603b73b7ffaf092a7e0/mail-parser-3.3.2.tar.gz
Requirement already satisfied: ipaddress in ./.local/lib/python3.6/site-packages (from mail-parser) (1.0.22)
Requirement already satisfied: simplejson in ./.local/lib/python3.6/site-packages (from mail-parser) (3.15.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from mail-parser) (1.11.0)
Installing collected packages: mail-parser
  Running setup.py install for mail-parser ... done
Successfully installed mail-parser-3.3.2
```

This means that mail-parser will fail to install on a fresh [docker ubuntu 18.04 image](https://hub.docker.com/r/_/ubuntu) as no locale is set by default.  (This was how I discovered this bug.)

```
$ docker run --rm -ti ubuntu
...
$ apt-get update
$ apt-get install -y python3 python3-pip
$ pip3 install mail-parser --user
Collecting mail-parser
  Downloading https://files.pythonhosted.org/packages/10/fa/988a3fe204d7cca689d75e623adf45a2f57c43e55603b73b7ffaf092a7e0/mail-parser-3.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-o3petv5z/mail-parser/setup.py", line 28, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6050: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-o3petv5z/mail-parser/
```

Again, setting a locale (e.g.: C.UTF-8) will fix the issue:

```
$ LC_CTYPE=C.UTF-8 pip3 install mail-parser --user
Collecting mail-parser
  Using cached https://files.pythonhosted.org/packages/10/fa/988a3fe204d7cca689d75e623adf45a2f57c43e55603b73b7ffaf092a7e0/mail-parser-3.3.2.tar.gz
Collecting ipaddress (from mail-parser)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting simplejson (from mail-parser)
  Downloading https://files.pythonhosted.org/packages/8b/6c/c512c32124d1d2d67a32ff867bb3cdd5bfa6432660975f7ee753ed7ad886/simplejson-3.15.0.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 1.1MB/s 
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from mail-parser)
Building wheels for collected packages: mail-parser, simplejson
  Running setup.py bdist_wheel for mail-parser ... done
  Stored in directory: /root/.cache/pip/wheels/b2/bf/36/983bad64964927fa0377c2a0d2b8265bb8e38514c49b025dbb
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /root/.cache/pip/wheels/2c/96/fb/b63af7400da79753dcd2a3f9bf5e7a3010e8d0233844445c2c
Successfully built mail-parser simplejson
Installing collected packages: ipaddress, simplejson, mail-parser
Successfully installed ipaddress-1.0.22 mail-parser-3.3.2 simplejson-3.15.0

```

**Comment by rudymatela** [comment]
This problem is caused when [`README.rst` (line 224)](https://github.com/SpamScope/mail-parser/blame/develop/README.rst#L224) is read by [`setup.py` (line 28)](https://github.com/SpamScope/mail-parser/blob/develop/setup.py#L28)

I can think of two ways to fix this issue:

1. force UTF-8 decode after the f.read() on line 28;
2. stop using UTF-8 on README.rst and stick to ASCII.  The issue is caused by the `├` character.

**Comment by fedelemantuano** [comment]
Thanks for your contribution. Yes I'm accepting both of them. I will check these PR and I will make a new release.

**Comment by fedelemantuano** [comment]
Hi @rudymatela,
I've just release a new version with your PRs.
[v3.3.3](https://github.com/SpamScope/mail-parser/releases/tag/v3.3.3)
