### ISSUE TITLE
KeyError: 'content-transfer-encoding'

### ISSUE THREAD

**Issue by Marenostrum81** [SpamScope/mail-parser#49]
I have some issue with an email from Paypal, as it hasn't any _'content-transfer-encoding'_ in the header.
Due to this I have an exception, originated by _replace_header function_ inside message.py

**To Reproduce**
1. `import mailparser`
2. (stuff for connection and retrieve the last unread email)
3. `mail = mailparser.parse_from_bytes(data[0][1])`

This is working good for the rest of the emails, but when I read the one who hasn't this header, then I have this exception:
``` 
exception=KeyError('content-transfer-encoding',)>
Traceback (most recent call last):
  File "C:/Users/BOHEM/imapbot/beta/imapbot.py", line 47, in connectMail
    body = await searchMail(imap4ssl)
  File "C:/Users/BOHEM/imapbot/beta/imapbot.py", line 26, in searchMail
    mail = mailparser.parse_from_bytes(data[0][1])
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\site-packages\mailparser\mailparser.py", line 115, in parse_from_bytes
    return MailParser.from_bytes(bt)
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\site-packages\mailparser\mailparser.py", line 238, in from_bytes
    return cls(message)
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\site-packages\mailparser\mailparser.py", line 135, in __init__
    self.parse()
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\site-packages\mailparser\mailparser.py", line 338, in parse
    p_string = ported_string(p.as_string())[:100] + "..."
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\email\message.py", line 158, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\email\generator.py", line 116, in flatten
    self._write(msg)
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\email\generator.py", line 181, in _write
    self._dispatch(msg)
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\email\generator.py", line 214, in _dispatch
    meth(msg)
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\email\generator.py", line 272, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\email\generator.py", line 116, in flatten
    self._write(msg)
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\email\generator.py", line 189, in _write
    **msg.replace_header('content-transfer-encoding', munge_cte[0])**
  File "C:\Users\BOHEM\AppData\Local\Programs\Python\Python36\lib\email\message.py", line 559, in replace_header
    **raise KeyError(_name)
KeyError: 'content-transfer-encoding'**
```

**Raw mail**
The raw mail to reproduce the behavior.
edited: (https://gist.github.com/Marenostrum81/dae5ce430687060832a9aa4b47d4d328).

**Environment:**
 - OS: [Windows]
 - Docker: [no]
 - mail-parser version [e.g. 3.8.1]

**Additional context**
For testing purposes, I modified **replace_header** _function_ in message.py, from this:

```
def replace_header(self, _name, _value):
        _name = _name.lower()
        for i, (k, v) in zip(range(len(self._headers)), self._headers):
            if k.lower() == _name:
                self._headers[i] = self.policy.header_store_parse(k, _value)
                break
        else:
            raise KeyError(_name)
```
To this:
```
def replace_header(self, _name, _value):
        _name = _name.lower()
        for i, (k, v) in zip(range(len(self._headers)), self._headers):
            if k.lower() == _name:
                self._headers[i] = self.policy.header_store_parse(k, _value)
                break
        else:
            pass
```

With this modification, the mailparser was parsing good the email, being able to read data from header, like mail.subject, mail.from_, mail.body, etc.

**Comment by fedelemantuano** [comment]
Hi @Marenostrum81,

I can't access your gist. Can you give me access to it?

**Comment by Marenostrum81** [comment]
https://gist.github.com/Marenostrum81/dae5ce430687060832a9aa4b47d4d328

**Comment by Marenostrum81** [comment]
> Hi @Marenostrum81,
> 
> I can't access your gist. Can you give me access to it?

https://gist.github.com/Marenostrum81/dae5ce430687060832a9aa4b47d4d328

**Comment by Marenostrum81** [comment]
> The first part of your email is not valid:
> 
> ```
> Mensaje original
> ID de mensaje	<fcnz-838575-2161405320-xt547vdya1-invite@mail.paypal-survey.com>
> Creado a las:	31 de enero de 2019, 22:26 (entregado en 3 segundos)
> De:	PayPal <invite@mail.paypal-survey.com>
> Para:	secret@gmail.com
> Asunto:	Comparta su opinión con nosotros
> SPF:	PASS con la IP 167.89.38.187 Más información
> DKIM:	'PASS' con el dominio mail.paypal-survey.com Más información
> DMARC:	'PASS' Más información
> 
> 
> Descargar original	Copiar en el portapapeles	
> ```
> I've just removed it and then I parsed the email correctly.
> 
> The output is [here](https://gist.github.com/fedelemantuano/ecb26e0faebaf5b3f8b2671e2e1f18ac).

If I read the message with _parse_from_bytes_ method, I continue with the same error.
If I save data[0][1] to file, and I use _parse_from_file_, it parses everything ok.

Sorry for the gist, as I copied it from gmail client as raw message. The email content is like you said, i will update it now with the correct format.

**Comment by fedelemantuano** [comment]
I'm checking this error, and I found this error in a bug Python [issue27321](https://bugs.python.org/issue27321).
In _mail-parser_ code this issue happen for a line of code `p.as_string()`.

**Comment by fedelemantuano** [comment]
I fixed this issue in `mail-parser` but this is an Python bug. From my analysis this header part

```
Content-Type: multipart/alternative;
        boundary="----=_NextPart_001_001F_01C26331.F7121560"
```

fires the error, but it's RFC correct. So I can't understand.

`mail-parser` uses `as_string()` for logging, so I changed it and works.

Thanks for your contribution.
