### ISSUE TITLE
Support for Python 3?

### ISSUE THREAD

**Issue by opsdisk** [SpamScope/mail-parser#5]
Edit: Just saw the developer branch you're working on.
---
Great library!  Byte, string, unicode issues introduced with Python 3

```
# mailparser -f test3.email -j                                                                                                   
Traceback (most recent call last):
  File "/home/test/.venv/bin/mailparser", line 11, in <module>
    load_entry_point('mail-parser==0.5.0', 'console_scripts', 'mailparser')()
  File "/home/test/.venv/lib/python3.5/site-packages/mailparser/__main__.py", line 140, in main
    parser.parse_from_file(args.file)
  File "/home/test/.venv/lib/python3.5/site-packages/mailparser/__init__.py", line 52, in parse_from_file
    self._parse()
  File "/home/test/.venv/lib/python3.5/site-packages/mailparser/__init__.py", line 192, in _parse
    encoding=charset)
  File "/home/test/.venv/lib/python3.5/site-packages/mailparser/__init__.py", line 86, in _force_unicode
    if not isinstance(u, unicode):
NameError: name 'unicode' is not defined
```

**Comment by fedelemantuano** [comment]
Hi @opsdisk you right. I'm working on this in #4.
