### ISSUE TITLE
Can not save attachments for emails with Content-Type: text/calendar

### ISSUE THREAD

**Issue by josephtingiris** [SpamScope/mail-parser#51]
**Describe the bug**

Using mailparser from the cli fails fatally on Content-Type: text/calendar

**To Reproduce**
1. `mailparser -f mail.txt -ap /var/tmp --store-attachments`
3. '....'

**Expected behavior**
The meeting attachment is written to disk as other (base64) attachments are.

**Raw mail**
Any raw mail containing a meeting request attachment, i.e.

```Return-Path: me@me.com
Received: from mail.me.com (LHLO mail.me.com) (10.0.1.80) by
 mail.me.com with LMTP; Fri, 8 Feb 2019 10:21:37 -0500 (EST)
Received: from localhost (localhost [127.0.0.1])
        by mail.me.com (Postfix) with ESMTP id 82E49C900985;
        Fri,  8 Feb 2019 10:21:37 -0500 (EST)
Received: from mail.me.com ([127.0.0.1])
        by localhost (mail.me.com [127.0.0.1]) (amavisd-new, port 10032)
        with ESMTP id Or1feO1BbrkB; Fri,  8 Feb 2019 10:21:36 -0500 (EST)
Received: from localhost (localhost [127.0.0.1])
        by mail.me.com (Postfix) with ESMTP id 875A1C90070B;
        Fri,  8 Feb 2019 10:21:36 -0500 (EST)
X-Quarantine-ID: <OUFU1ymuNiJU>
X-Virus-Scanned: amavisd-new at mail.me.com
Received: from mail.me.com ([127.0.0.1])
        by localhost (mail.me.com [127.0.0.1]) (amavisd-new, port 10026)
        with ESMTP id OUFU1ymuNiJU; Fri,  8 Feb 2019 10:21:36 -0500 (EST)
Received: from mail.me.com (mail.me.com [10.0.1.80])
        by mail.me.com (Postfix) with ESMTP id 5C626C9000C9;
        Fri,  8 Feb 2019 10:21:36 -0500 (EST)
Date: Fri, 8 Feb 2019 10:21:36 -0500 (EST)
From: me@me.com
To: Me Too <metoo@me.com>
Message-ID: <1587851191.6960234.1549639296328.JavaMail.zimbra@me.com>
Subject: Project Meeting
MIME-Version: 1.0
Content-Type: multipart/alternative; 
        boundary="----=_Part_6960233_303396869.1549639296326"
X-Originating-IP: [10.0.2.1]
X-Mailer: Zimbra 8.6.0_GA_1194 (ZimbraWebClient - GC72 (Win)/8.6.0_GA_1194)

------=_Part_6960233_303396869.1549639296326
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

A single instance of the following meeting has been modified:

Subject: Project Meeting 
Organizer: "Me Me" <me@me.com> 

Location: "Conference Room" <conferenceroom@me.com> 
Resources: "Conference Room" <conferenceroom@me.com> (Conference Room) 
Time: Friday, February 8, 2019, 11:00:00 AM - 12:00:00 PM GMT -05:00 US/Canada Eastern
 
Invitees: metoo@me.com ... 


*~*~*~*~*~*~*~*~*~*

The following meeting has been modified:

Subject: Project Meeting 
Organizer: "Me Me" <me@me.com> 

Location: "Conference Room" <conferenceroom@me.com> 
Resources: "Conference Room" <conferenceroom@me.com> (Conference Room) 
Time: 11:00:00 AM - 12:00:00 PM GMT -05:00 US/Canada Eastern [MODIFIED]
 Recurrence : Every Friday.   End by Jun 28, 2019.   Effective Oct 26, 2018

Invitees: metoo@me.com ... 


*~*~*~*~*~*~*~*~*~*

Creating new series to fix conference room issue 

------=_Part_6960233_303396869.1549639296326
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html><body id='htmlmode'><h3>A single instance of the following meeting has been modified:</h3>

<p>
<table border='0'>
<tr><th align=left>Subject:</th><td>Project Meeting </td></tr>
<tr><th align=left>Organizer:</th><td>"Me Me" &lt;me@me.com&gt; </td></tr>
</table>
<p>
<table border='0'>
<tr><th align=left>Location:</th><td>"Conference Room" &lt;conferenceroom@me.com&gt; </td></tr>
<tr><th align=left>Resources:</th><td>"Conference Room" &lt;conferenceroom@me.com&gt; (Conference Room) </td></tr>
<tr><th align=left>Time:</th><td>Friday, February 8, 2019, 11:00:00 AM - 12:00:00 PM GMT -05:00 US/Canada Eastern
 </td></tr></table>
<p>
<table border='0'>
<tr><th align=left>Invitees:</th><td>metoo@me.com ... </td></tr>
</table>
<div>*~*~*~*~*~*~*~*~*~*</div><br><div style="font-family: tahoma,new york,times,serif; font-size: 12pt; color: #000000"><div style="font-family: tahoma,new york,times,serif; font-size: 12pt; color: #000000"><div>Creating new series to fix conference room issue</div></div></div></body></html>
------=_Part_6960233_303396869.1549639296326
Content-Type: text/calendar; charset=utf-8; method=CANCEL; name=meeting.ics
Content-Transfer-Encoding: 7bit

BEGIN:VCALENDAR
PRODID:Zimbra-Calendar-Provider
VERSION:2.0
METHOD:CANCEL
BEGIN:VTIMEZONE
TZID:America/New_York
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETTO:-0500
TZOFFSETFROM:-0400
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU
TZNAME:EST
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETTO:-0400
TZOFFSETFROM:-0500
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=2SU
TZNAME:EDT
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:77b6c34a-ec9c-4d34-8552-2896f3ab5996
SUMMARY:Project Meeting
COMMENT:A single instance of a recurring meeting has been modified.
LOCATION:"Conference Room" <conferenceroom@me
 .com>
ATTENDEE;CN=Me Too;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED:mailto:m
 etoo@me.com
ATTENDEE;CN=Conference Room;CUTYPE=RESOURCE;ROLE=NON-PARTI
 CIPANT;PARTSTAT=ACCEPTED:mailto:conferenceroom@me.com
ORGANIZER;CN=Me Me:mailto:me@me.com
DTSTART;TZID="America/New_York":20190208T110000
DTEND;TZID="America/New_York":20190208T120000
STATUS:CANCELLED
CLASS:PUBLIC
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
TRANSP:OPAQUE
RECURRENCE-ID;TZID="America/New_York":20190208T110000
LAST-MODIFIED:20190208T152136Z
DTSTAMP:20190208T152136Z
SEQUENCE:2
DESCRIPTION:A single instance of the following meeting has been modified:\n
 \nSubject: Project Meeting \nOrganizer: "Me Me" <me@me
 .com> \n\nLocation: "Conference Room" <confer
 enceroom@me.com> \nResources: "Conference Room" <
 conferenceroom@me.com> (Conference Room) \nT
 ime: Friday\, February 8\, 2019\, 11:00:00 AM - 12:00:00 PM GMT -05:00 US/Ca
 nada Eastern\n \nInvitees: metoo@me.com ... \n\n\n*~*~*~*~*~*~*~*
 ~*~*\n\nThe following meeting has been modified:\n\nSubject: Projec
 t Meeting \nOrganizer: "Me Me" <me@me.com> \n\nLocation: "IT - 
 Earl's Court Conference Room" <conferenceroom@me.com> \nRe
 sources: "Conference Room" <conferenceroom@me
 me.com> (Conference Room) \nTime: 11:00:00 AM - 12:00:0
 0 PM GMT -05:00 US/Canada Eastern [MODIFIED]\n Recurrence : Every Friday.   
 End by Jun 28\, 2019.   Effective Oct 26\, 2018\n\nInvitees: metoo@me
 .com ... \n\n\n*~*~*~*~*~*~*~*~*~*\n\nCreating new series to fix confere
 nce room issue \n
X-ALT-DESC;FMTTYPE=text/html:<html><body id='htmlmode'><h3>A single instance
  of the following meeting has been modified:</h3>\n\n<p>\n<table border='0'
 >\n<tr><th align=left>Subject:</th><td>Project Meeting </td></tr>\n
 <tr><th align=left>Organizer:</th><td>"Me Me" &lt\;me@me.com&gt
 \; </td></tr>\n</table>\n<p>\n<table border='0'>\n<tr><th align=left>Locatio
 n:</th><td>"Conference Room" &lt\;conferencer
 oom@me.com&gt\; </td></tr>\n<tr><th align=left>Resources:</th><td>"IT -
  Earl's Court Conference Room" &lt\;conferenceroom@me.com&
 gt\; (Conference Room) </td></tr>\n<tr><th align=left>Time
 :</th><td>Friday\, February 8\, 2019\, 11:00:00 AM - 12:00:00 PM GMT -05:00 
 US/Canada Eastern\n </td></tr></table>\n<p>\n<table border='0'>\n<tr><th ali
 gn=left>Invitees:</th><td>metoo@me.com ... </td></tr>\n</table>\n
 <div>*~*~*~*~*~*~*~*~*~*</div><br><div style="font-family: tahoma\,new york\
 ,times\,serif\; font-size: 12pt\; color: #000000"><div style="font-family: t
 ahoma\,new york\,times\,serif\; font-size: 12pt\; color: #000000"><div>Creat
 ing new series to fix conference room issue</div></div></div></body></html>
END:VEVENT
END:VCALENDAR
------=_Part_6960233_303396869.1549639296326--
```

**Environment:**
 - OS: Linux
 - Docker: no
 - mail-parser version 3.9.2

**Additional context**
Add any other context about the problem here (e.g. stack traceback error).

```Traceback (most recent call last):
  File "/usr/bin/mailparser", line 9, in <module>
    load_entry_point('mail-parser==3.9.2', 'console_scripts', 'mailparser')()
  File "/usr/lib/python3.4/site-packages/mail_parser-3.9.2-py3.4.egg/mailparser/__main__.py", line 260, in main
    write_attachments(parser.attachments, args.attachments_path)
  File "/usr/lib/python3.4/site-packages/mail_parser-3.9.2-py3.4.egg/mailparser/utils.py", line 527, in write_attachments
    filename=a["filename"],
  File "/usr/lib/python3.4/site-packages/mail_parser-3.9.2-py3.4.egg/mailparser/utils.py", line 552, in write_sample
    f.write(payload.encode("utf-8"))
TypeError: must be str, not bytes
```

**Comment by fedelemantuano** [comment]
From my first test this error happens only on Python 3.x.

**Comment by fedelemantuano** [comment]
Hi @josephtingiris,

thanks for reporting.
