### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by kojibhy** [SpamScope/mail-parser#7]
File "/root/PythonProjects/venv/lib/python3.5/site-packages/mailparser/mailparser.py", line 59, in parse_from_string
    self._parse()
  File "/root/PythonProjects/venv/lib/python3.5/site-packages/mailparser/mailparser.py", line 169, in _parse
    self._make_mail()
  File "/root/PythonProjects/venv/lib/python3.5/site-packages/mailparser/mailparser.py", line 95, in _make_mail
    "to": self.to_,
  File "/root/PythonProjects/venv/lib/python3.5/site-packages/mailparser/mailparser.py", line 237, in to_
    self._message.get('to', self._message.get('delivered-to')))
  File "/root/PythonProjects/venv/lib/python3.5/site-packages/mailparser/utils.py", line 80, in decode_header_part
    for d, c in decode_header(header):
  File "/usr/lib/python3.5/email/header.py", line 80, in decode_header
    if not ecre.search(header):
TypeError: expected string or bytes-like object

**Comment by fedelemantuano** [comment]
Hi @kojibhy,

can you give me more details? 
What is your input? So I can understand what's happen.

**Comment by kojibhy** [comment]
Hi, i am using Python3:
cannot decode many fields this is exemple:
b'"\xdd\xca\xc2\xc0\xc9\xd0\xc8\xcd\xc3" <acquiring@tkbbank.ru>'


sometimes i get this:

Traceback (most recent call last):
  File "/root/PythonProjects/venv/lib/python3.5/site-packages/mailparser/utils.py", line 71, in ported_string
    return six.text_type(raw_data, encoding).strip()
LookupError: unknown encoding: unknown-8bit


and this:

  File "/root/PythonProjects/venv/lib/python3.5/site-packages/mailparser/utils.py", line 73, in ported_string
    return six.text_type(raw_data, "utf-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 41: invalid continuation byte

**Comment by fedelemantuano** [comment]
`mailparser` can't use encoding of mail because it's not known and fail the parsing.

```
LookupError: unknown encoding: unknown-8bit
```

Can you give me the raw mail?

**Comment by kojibhy** [comment]
yes where i can send it

**Comment by fedelemantuano** [comment]
Hi @kojibhy,
you could make a new [gist](https://gist.github.com/).

**Comment by fedelemantuano** [comment]
Hi @kojibhy,

can you give me an update?

**Comment by kojibhy** [comment]
i collect error msg for you, but i can`t share this msg in public

**Comment by fedelemantuano** [comment]
I tested all your mail with version 1.2.0 and I didn't have any errors. So I can close this issue.
